include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_put_required_named_parameters_first: false
    prefer_const_declarations: false
    sort_pub_dependencies: false